name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        name: "${{ env.GITHUB_SHA }}"
        files: package.json
